infile = open('PE5_4.txt','a')
input1 = input('Date: ')
input2 = input('Time: ')
input3 = input('Name: ')
infile.write(input1)
infile.write(', ')
infile.write(input2)
infile.write(', ')
infile.write(input3)
infile.write('\n')
infile.close()